### ISSUE TITLE
Error in fitting glmer models

### ISSUE THREAD

**Issue by arcuo** [LudvigOlsen/cvms#7] opened 2016-12-07 12:07 UTC
I tried fitting several (silly) models with cross_validate_list, but the function would stop, instead of just returning NA's for the model. I added TryCatch to each of the fit_model_ parts. That fixed it.

fit_model_ = function(model, model_type, training_set, family, REML, model_verbose){
  
# My version of fit_model_

 _Checks the model_type and fits the model on the training_set_
  
  if (model_type == 'lm'){
    
    if (model_verbose == TRUE){
      print('Used lm()')}
    
    _Fit the model using lm()_
    _Return this model to model_temp_
    return(tryCatch({
      
      lme4::lm(model,training_set)
      
    }, error = function(e){
      
      print("Model return error.")
      return(NULL)
      
    }))
    
  } else if (model_type == 'lmer'){
    
    if (model_verbose == TRUE){
      print('Used lme4::lmer()')}
    
    _Fit the model using lmer()_
    _Return this model to model_temp_
    return(tryCatch({
      
      lme4::lmer(model,training_set, REML = REML)
      
    }, error = function(e){
      
      print("Model return error.")
      return(NULL)
      
    }))
    
  } else if (model_type == 'glm'){
    
    if (model_verbose == TRUE){
      print('Used glm()')}
    
    _Fit the model using glm()_
    _Return this model to model_temp_
    return(tryCatch({
      
      lme4::glm(model,training_set, family = family)
      
    }, error = function(e){
      
      print("Model return error.")
      return(NULL)
      
    }))
    
  } else if (model_type == 'glmer'){
    
    if (model_verbose == TRUE){
      print('Used lme4::glmer()')}
    
    _Fit the model using glmer()_
    _Return this model to model_temp_
    return(tryCatch({
    
      lme4::glmer(model,training_set, family = family)
      
    }, error = function(e){
      
      print("Model return error.")
      return(NULL)
      
    }))
  
  }
  
  
}

**Comment by LudvigOlsen** [comment] 2017-05-25 19:55
Couldn't reproduce the problem. Changed the parts a bit anyway since you posted it. Closing topic :)

**Closed by LudvigOlsen** 2017-05-25 19:55 UTC
