### ISSUE TITLE
Supplied Probabilities

### ISSUE THREAD

**Issue by daviddalpiaz** [LudvigOlsen/cvms#13] opened 2020-09-27 23:56 UTC
I'm curious if this statement from the documentation is true? (The added emphasis is mine.)

- "One column with the probability of class being the **second class alphabetically**."

Could it actually be the case that what actually matters is the second **level** when the target column is a factor?

**Comment by LudvigOlsen** [comment] 2020-09-30 19:12
Hi David,

I just had a look, and it seems you're right. I've made a note to fix this for the next release.
Thanks for making me aware!

Best,
Ludvig

**Comment by daviddalpiaz** [comment] 2020-09-30 21:08
Hi Ludvig,

By the way, I love the package. It's nearly perfect for use in a statistical learning class I teach at University of Illinois. If I had a wish-list:

- In addition to specifying positive-negative, also allow users to specify which class is 0 and 1 mathematically. One of the best things about the `evaluate()` function IMO is the verbosity of user input. 
- Any reason why `Accuracy` is not returned by default? With so many metrics already being returned, I was quite surprised to see I needed to request this one specifically.
- Can I assume there is a reason why eval_results$`Confusion Matrix` returns a list and not just the confusion matrix? (There seems to be some way to do multiple evaluations, but I haven't tested. I guess I'm maybe more wondering out loud if there is only one evaluation if this could be simplified. Perhaps that's asking way too much.)
- The above list element name "Confusion Matrix" having a space in it makes it really hard for me to format it as code in this reply!

Sorry to be so nit-picky! Just super excited my how useful the package is already.

-David

**Comment by LudvigOlsen** [comment] 2020-10-01 06:48
Great! I'm very open to ideas for improvements :)

> In addition to specifying positive-negative, also allow users to specify which class is 0 and 1 mathematically. One of the best things about the evaluate() function IMO is the verbosity of user input.

Can you give an example of what this could look like?

> Any reason why Accuracy is not returned by default? With so many metrics already being returned, I was quite surprised to see I needed to request this one specifically.

Historically, the metrics were chosen for model selection in the cross_validate() function. At some point, I replaced Accuracy with Balanced Accuracy, as it seems a better criterion with imbalanced datasets. Of course this is no reason not to have it in evaluate() by default, so I can enable it in that function.

> Can I assume there is a reason why eval_results$Confusion Matrix returns a list and not just the confusion matrix? 

That's how dataframes can be nested, as far as I'm aware. I do get that it's annoying to write the [[1]] though. I believe `plot_confusion_matrix()` works directly on the output tibble, but if you want the raw confusion matrix, I'm not sure how to get around the indexing.

> The above list element name "Confusion Matrix" having a space in it makes it really hard for me to format it as code in this reply!

Haha, I see! You could use `eval_results[["Confusion Matrix"]]`. That should work?

Do post whenever you have a suggestion. I'm currently quite busy during the week, but I hope to find time for improvements soon :)

**Comment by daviddalpiaz** [comment] 2020-10-01 22:30
In a binary classification problem, you can work with the probabilities for either class. Right now, `evaluate()` forces you to work with the probabilities for the second level. The cutoff only applies to this class. If I supplied probabilities for the first class, it wouldn't work.

Using `eval_results[["Confusion Matrix"]]` still returns a list, not the data frame storing the confusion matrix. Perhaps I'm not sure what you mean by data frame nesting. But here's an example of sorting a data frame in a list element and extracting it.

```
some_list = list(
  yxz = data.frame(
    a = 1:10,
    b = 5
  )
)

some_list$xyz
```

But now that I've created this example, I realize that `evaluate()` actually returns a `tibble`. Any reason it couldn't return just a regular old list? I'm not seeing how a `tibble` is more useful here, and using a generic list would allow for the above.

**Comment by LudvigOlsen** [comment] 2020-10-02 11:36
As it is binary classification we are evaluating, the probability of the first class (say `P1`) is by definition `1-P2`. So we do have access to them. But what would you do with them? If you want the other class to be the positive class, you just set positive=1. If you only have the probabilities of the first class, you use the `P2 = 1-P1` formula to get them for class 2.

Confusion Matrix: As they are nested (see [here](https://tidyr.tidyverse.org/articles/nest.html)) in a column, the column becomes a list of confusion matrices (one per row). Only when you have a single row would it be possible to avoid the indexing by using a list. And `evaluate()` allows you to evaluate grouped data frames (e.g. if you have collected the predictions of multiple classifiers (SVM, logistic regression, etc.)), so it will often have more than one row in the output. This is also the case for the `cross_validate(_fn)` functions, where you want to compare multiple models, and I prefer for them to have the same output format. 
Lists also don't print very nicely.

If you think it would be helpful though, I can add helper functions (like `get_confusion_matrix()`)?

Additionally, I'm thinking of adding a small report, either as attributes in the tibble or just printing it, that states what class the probabilities were of, what class was the positive class, etc. If I can find a good approach, it might make it clearer (and catch potential mistakes).

**Comment by LudvigOlsen** [comment] 2020-10-02 11:39
Note that you can also use the multinomial evaluation with 2 classes. The included `Class Level Results` have the evaluations for each of the classes. The probabilities (`P1` and `P2`) still need to sum to 1 though.

**Comment by daviddalpiaz** [comment] 2020-10-02 13:46
On using `p1` vs `p2`: Assuming they're in that order, from what I currently understand, `evaluate()` only makes classifications based on `p2`. So whatever `cutoff` is supplied, you'll get classifications based on `p2 > cutoff`. This is still true if you set `p1` to be positive. (Basically, I'm poking at this because I gave my students a problem where I gave a cutoff based on `p1` and then chaos ensued. But I sort of get where they're coming from.)

**Comment by LudvigOlsen** [comment] 2020-10-02 16:53
Right, I see that can be confusing. Yes, the `cutoff` and `positive` arguments don't interact (as far as I recall). The probability is expected to be of `p2`, and so, values over `cutoff` are considered predictions of `p2`. Then we get to the actual evaluation, where we choose one of them as the positive class.

I'll consider making this pipeline clearer, e.g. in a vignette, so it's clear what goes on. I guess some kind of graph visualization might also be useful in your teaching? 

It's great that you bring this confusion to my attention, so I can improve the communication in the package :)

**Comment by daviddalpiaz** [comment] 2020-10-02 16:56
There's actually part of me that likes the "confusion." Aside from the minor detail about alphabetical versus level ordering, the documentation does spell this out. Students are just failing at the implied part of the questions that want them to read the documentation!

**Comment by LudvigOlsen** [comment] 2020-10-02 17:01
To be fair, my function help pages tend to get quite long... But adding documentation when the problem is that they don't read the documentation is of course of too helpful! :-)
I do like the idea of some visuals explaining the pipeline for the various functions. That tends to make things clear quickly.

**Comment by LudvigOlsen** [comment] 2020-10-03 10:09
I'm working on adding information about the evaluation process to the output. This is the information I'm currently giving:

<img width="470" alt="Screen Shot 2020-10-03 at 12 05 18" src="https://user-images.githubusercontent.com/22819047/94988890-d43a5200-0570-11eb-80e9-30c68e60318d.png">

Anything you would like to include?

I'm considering whether this should be printed automatically when calling `evaluate()`. Just for the first row (evaluation). Not sure whether that might clutter the output too much though.

**Comment by daviddalpiaz** [comment] 2020-10-03 13:20
Oooh. This likes nice. Two comments:

1. What happens when the prediction probability equals 0.5?
2. That last bit about the locale information for sorting implies to me that the response variable is being sorted. Does this mean it won't respect the ordering of the factor that was passed?

**Comment by LudvigOlsen** [comment] 2020-10-03 13:26
1. Right, my mistake. That should of course be added. It's `>=`.
 2. In order to actually have it be the second level *alphabetically*, I sort the levels when extracting them yes. I'll make the message more clear.

**Comment by daviddalpiaz** [comment] 2020-10-03 13:32
On (2) I guess I'm wondering if that's a desired feature. For example, users are probably used to the notion of the second level being the "Y = 1" category from the way `glm()` handles logistic regression. I wonder if mirroring that would cause less friction. (I suppose this is actually a pretty rare edge case since the vast majority of the time the factor is already ordered alphabetically.)

**Comment by LudvigOlsen** [comment] 2020-10-03 13:42
Considering your last note, I think it's a lot easier to specify that it's the second level alphabetically (for numerics, characters, and factors), compared to: for numerics and characters, but not necessarily for factors.

**Comment by daviddalpiaz** [comment] 2020-10-03 22:54
Ah, that makes sense. I didn't really consider non-factor variables.

**Comment by LudvigOlsen** [comment] 2020-10-08 05:27
@daviddalpiaz 
Hi David,
I've fixed the original issue in the new release. :)
I'm closing the issue, but feel free to start a new one (or open it again) at any time. Thanks a lot for your feedback :)

Best,
Ludvig

**Closed by LudvigOlsen** 2020-10-08 05:27 UTC
Labels: bug
